EcruteakCity_SageOffice1_MapScripts::
	.byte 0

@ Johto map scripts (imported from HnS, stubs)

EcruteakCity_SageOffice1_EventScript_Sign::
	msgbox EcruteakCity_SageOffice_Text_Sign, MSGBOX_SIGN
	end

EcruteakCity_SageOffice2_EventScript_SageA::
	msgbox EcruteakCity_SageOffice_Text_SageA, MSGBOX_NPC
	end

EcruteakCity_SageOffice2_EventScript_SageB::
	msgbox EcruteakCity_SageOffice_Text_SageB, MSGBOX_NPC
	end

EcruteakCity_SageOffice2_EventScript_SageC::
	msgbox EcruteakCity_SageOffice_Text_SageC, MSGBOX_NPC
	end

EcruteakCity_SageOffice_Text_Sign:
	.string "ECRUTEAK DANCE THEATER\n"
	.string "Office of the Sages$"

EcruteakCity_SageOffice_Text_SageA:
	.string "The KIMONO GIRLS carry on\n"
	.string "an ancient tradition.\p"
	.string "Their dances are prayers\n"
	.string "for peace and prosperity.$"

EcruteakCity_SageOffice_Text_SageB:
	.string "TIN TOWER was built long ago\n"
	.string "as a perch for HO-OH.\p"
	.string "BURNED TOWER once served\n"
	.string "the same purpose for LUGIA.$"

EcruteakCity_SageOffice_Text_SageC:
	.string "Three POKeMON perished in\n"
	.string "the fire that burned the\l"
	.string "tower.\p"
	.string "HO-OH revived them as the\n"
	.string "legendary beasts: ENTEI,\l"
	.string "RAIKOU, and SUICUNE.$"

