SSAqua_B1F_MapScripts::
	.byte 0

@ Johto map scripts (imported from HnS, stubs)

SSAqua_B1F_EventScript_Barfcan::
	return

SSAqua_B1F_EventScript_Debra::
	return

SSAqua_B1F_EventScript_Fritz::
	return

SSAqua_B1F_EventScript_Garrett::
	return

SSAqua_B1F_EventScript_Jonah::
	return

SSAqua_B1F_EventScript_Kenneth::
	return

SSAqua_B1F_EventScript_Nate::
	return

SSAqua_B1F_EventScript_Ricky::
	return

SSAqua_B1F_EventScript_SailorLookingForBuddy::
	return

SSAqua_B1F_EventScript_Shirley::
	return

SSAqua_B1F_EventScript_SleepySailor::
	return

SSAqua_B1F_EventScript_Trigger::
	return

SSAqua_B1F_EventScript_Wai::
	return

