NationalPark_Normal_MapScripts::
	.byte 0

@ Johto map scripts (imported from HnS, stubs)

NationalPark_Normal_EventScript_Beverly::
	msgbox NationalPark_Normal_Text_Beverly, MSGBOX_NPC
	end

NationalPark_Normal_EventScript_Item_Soothe_Bell::
	msgbox NationalPark_Normal_Text_Item_Soothe_Bell, MSGBOX_NPC
	end

NationalPark_Normal_EventScript_Jack::
	msgbox NationalPark_Normal_Text_Jack, MSGBOX_NPC
	end

NationalPark_Normal_EventScript_Krise::
	msgbox NationalPark_Normal_Text_Krise, MSGBOX_NPC
	end

NationalPark_Normal_EventScript_Lass::
	msgbox NationalPark_Normal_Text_Lass, MSGBOX_NPC
	end

NationalPark_Normal_EventScript_Persian::
	msgbox NationalPark_Normal_Text_Persian, MSGBOX_NPC
	end

NationalPark_Normal_EventScript_TM_Dig::
	msgbox NationalPark_Normal_Text_TM_Dig, MSGBOX_NPC
	end

NationalPark_Normal_EventScript_Teacher2::
	msgbox NationalPark_Normal_Text_Teacher2, MSGBOX_NPC
	end

NationalPark_Normal_EventScript_TeacherQuickclaw::
	msgbox NationalPark_Normal_Text_TeacherQuickclaw, MSGBOX_NPC
	end

NationalPark_Normal_EventScript_William::
	msgbox NationalPark_Normal_Text_William, MSGBOX_NPC
	end

NationalPark_Normal_EventScript_Youngster1::
	msgbox NationalPark_Normal_Text_Youngster1, MSGBOX_NPC
	end

NationalPark_Normal_EventScript_Youngster2::
	msgbox NationalPark_Normal_Text_Youngster2, MSGBOX_NPC
	end

NationalPark_Normal_Text_Lass:
	.string "I love walking around town.\n"
	.string "The fresh air is wonderful!$"


NationalPark_Normal_Text_Beverly:
	.string "...$"

NationalPark_Normal_Text_Item_Soothe_Bell:
	.string "...$"

NationalPark_Normal_Text_Jack:
	.string "...$"

NationalPark_Normal_Text_Krise:
	.string "...$"

NationalPark_Normal_Text_Persian:
	.string "...$"

NationalPark_Normal_Text_TM_Dig:
	.string "...$"

NationalPark_Normal_Text_Teacher2:
	.string "Knowledge is the key to\nbecoming a great TRAINER!$"

NationalPark_Normal_Text_TeacherQuickclaw:
	.string "Knowledge is the key to\nbecoming a great TRAINER!$"

NationalPark_Normal_Text_William:
	.string "...$"

NationalPark_Normal_Text_Youngster1:
	.string "I want to be the best TRAINER\nin all of JOHTO!$"

NationalPark_Normal_Text_Youngster2:
	.string "I want to be the best TRAINER\nin all of JOHTO!$"
