MahoganyTown_RocketHideout_B2F_MapScripts::
	.byte 0

@ Mahogany Town Rocket Hideout scripts (stubs)

RocketHideout_B2F_EventScript_Electrode::
	msgbox RocketHideout_B2F_Text_Electrode, MSGBOX_NPC
	end

RocketHideout_B2F_EventScript_Grunt14::
	msgbox RocketHideout_B2F_Text_Grunt14, MSGBOX_NPC
	end

RocketHideout_B2F_EventScript_Grunt15::
	msgbox RocketHideout_B2F_Text_Grunt15, MSGBOX_NPC
	end

RocketHideout_B2F_EventScript_Grunt16::
	msgbox RocketHideout_B2F_Text_Grunt16, MSGBOX_NPC
	end

RocketHideout_B2F_EventScript_Lance::
	msgbox RocketHideout_B2F_Text_Lance, MSGBOX_NPC
	end

RocketHideout_B2F_EventScript_LanceTriggerLeft::
	return

RocketHideout_B2F_EventScript_LanceTriggerRight::
	return

RocketHideout_B2F_EventScript_ReadyForBattlePrompt::
	msgbox RocketHideout_B2F_Text_ReadyForBattlePrompt, MSGBOX_NPC
	end

RocketHideout_B2F_Trigger_Ariana::
	return

RocketHideout_B2F_Trigger_Electrode::
	return

RocketHideout_B2F_Trigger_MurkrowGate::
	return

RocketHideout_B2F_Trigger_MurkrowStairs::
	return

RocketHideout_EventScript_Item_Thief::
	msgbox RocketHideout_Text_Item_Thief, MSGBOX_NPC
	end

RocketHideout_B2F_Text_Lance:
	.string "LANCE: Dragons are the\n"
	.string "strongest POKeMON.\pBut true strength comes from\n"
	.string "the bond between TRAINER\land POKeMON.$"


RocketHideout_B2F_Text_Electrode:
	.string "...$"

RocketHideout_B2F_Text_Grunt14:
	.string "...$"

RocketHideout_B2F_Text_Grunt15:
	.string "...$"

RocketHideout_B2F_Text_Grunt16:
	.string "...$"

RocketHideout_B2F_Text_ReadyForBattlePrompt:
	.string "...$"

RocketHideout_Text_Item_Thief:
	.string "...$"
