VioletCity_House1_MapScripts::
	.byte 0

@ Johto map scripts (imported from HnS, stubs)

VioletCity_House1_EventScript_Kyle::
	msgbox VioletCity_House1_Text_Kyle, MSGBOX_NPC
	end

VioletCity_House1_EventScript_Rudy::
	msgbox VioletCity_House1_Text_Rudy, MSGBOX_NPC
	end

VioletCity_House1_Text_Kyle:
	.string "I trade POKeMON with my friend\n"
	.string "all the time! Trading makes\lPOKeMON grow faster!$"

VioletCity_House1_Text_Rudy:
	.string "Hey, did you know ONIX can\n"
	.string "evolve if you trade it while\lit's holding a METAL COAT?$"

