Gate_GoldenrodCity_Route35_MapScripts::
	.byte 0

@ Johto map scripts (imported from HnS, stubs)

Gate_GoldenrodCity_Route35_EventScript_Fisher::
	msgbox Gate_GoldenrodCity_Route35_Text_Fisher, MSGBOX_NPC
	end

Gate_GoldenrodCity_Route35_EventScript_Lady::
	msgbox Gate_GoldenrodCity_Route35_Text_Lady, MSGBOX_NPC
	end

Gate_GoldenrodCity_Route35_EventScript_Randy::
	msgbox Gate_GoldenrodCity_Route35_Text_Randy, MSGBOX_NPC
	end

Gate_GoldenrodCity_Route35_Text_Fisher:
	.string "You can fish up all sorts of\n"
	.string "rare POKeMON in JOHTO's waters!\pYou just need patience!$"


Gate_GoldenrodCity_Route35_Text_Lady:
	.string "...$"

Gate_GoldenrodCity_Route35_Text_Randy:
	.string "...$"
