Route35_MapScripts::
	.byte 0

@ Johto map scripts (imported from HnS, stubs)

Route35_EventScript_BirdKeeperBryan::
	msgbox Route35_Text_BirdKeeperBryan, MSGBOX_NPC
	end

Route35_EventScript_BugCatcherArnie::
	msgbox Route35_Text_BugCatcherArnie, MSGBOX_NPC
	end

Route35_EventScript_CamperElliot::
	msgbox Route35_Text_CamperElliot, MSGBOX_NPC
	end

Route35_EventScript_CamperIvan::
	msgbox Route35_Text_CamperIvan, MSGBOX_NPC
	end

Route35_EventScript_FirebreatherWalt::
	msgbox Route35_Text_FirebreatherWalt, MSGBOX_NPC
	end

Route35_EventScript_Item_Nugget::
	finditem ITEM_NUGGET
	end

Route35_EventScript_Item_ParalyzeHeal::
	msgbox Route35_Text_Item_ParalyzeHeal, MSGBOX_NPC
	end

Route35_EventScript_Item_RockTomb::
	msgbox Route35_Text_Item_RockTomb, MSGBOX_NPC
	end

Route35_EventScript_JugglerIrwin::
	msgbox Route35_Text_JugglerIrwin, MSGBOX_NPC
	end

Route35_EventScript_PicnickerBrooke::
	msgbox Route35_Text_PicnickerBrooke, MSGBOX_NPC
	end

Route35_EventScript_PicnickerKim::
	msgbox Route35_Text_PicnickerKim, MSGBOX_NPC
	end

Route35_EventScript_PolicemanDirk::
	msgbox Route35_Text_PolicemanDirk, MSGBOX_NPC
	end

Route35_EventScript_Sign1::
	msgbox Route35_Text_Sign1, MSGBOX_SIGN
	end

Route35_EventScript_Sign2::
	msgbox Route35_Text_Sign2, MSGBOX_SIGN
	end


Route35_Text_BirdKeeperBryan:
	.string "My bird POKeMON soar through\nthe skies!$"

Route35_Text_BugCatcherArnie:
	.string "BUG POKeMON are the best!\nI love catching them!$"

Route35_Text_CamperElliot:
	.string "Nothing beats camping under\nthe stars with POKeMON!$"

Route35_Text_CamperIvan:
	.string "Nothing beats camping under\nthe stars with POKeMON!$"

Route35_Text_FirebreatherWalt:
	.string "...$"

Route35_Text_Item_ParalyzeHeal:
	.string "...$"

Route35_Text_Item_RockTomb:
	.string "...$"

Route35_Text_JugglerIrwin:
	.string "...$"

Route35_Text_PicnickerBrooke:
	.string "I love having lunch with\nmy POKeMON outdoors!$"

Route35_Text_PicnickerKim:
	.string "I love having lunch with\nmy POKeMON outdoors!$"

Route35_Text_PolicemanDirk:
	.string "This is a nice place.\nThe people here are friendly.$"

Route35_Text_Sign1:
	.string "Route35$"

Route35_Text_Sign2:
	.string "Route35$"
