#ifndef GUARD_CONSTANTS_JOHTO_CONSTANTS_H
#define GUARD_CONSTANTS_JOHTO_CONSTANTS_H

// Auto-generated stub constants for Johto maps from HnS
// These are placeholders - replace with real values when scripting Johto

// Johto script variables
#define VAR_AZALEA_TOWN_STATE                         (0x4100 + 0)
#define VAR_BLACKTHORN_CITY_STATE                     (0x4100 + 1)
#define VAR_BLACKTHORN_GYM_STATE                      (0x4100 + 2)
#define VAR_CHERRYGROVE_CITY_STATE                    (0x4100 + 3)
#define VAR_COMPLETED_HO_OH                           (0x4100 + 4)
#define VAR_COMPLETED_LUGIA                           (0x4100 + 5)
#define VAR_ECRUTEAK_CITY_STATE                       (0x4100 + 6)
#define VAR_ECRUTEAK_CITY_THEATER                     (0x4100 + 7)
#define VAR_GOLDENROD_CITY_STATE                      (0x4100 + 8)
#define VAR_ICE_PATH_STATE                            (0x4100 + 9)
#define VAR_ILEX_FOREST_FARFETCHD                     (0x4100 + 10)
#define VAR_LUGIA_OR_HOOH                             (0x4100 + 11)
#define VAR_MAHOGANY_TOWN_STATE                       (0x4100 + 12)
#define VAR_NEWBARKTOWN_LABSTATE                      (0x4100 + 13)
#define VAR_NEWBARK_TOWN_STATE                        (0x4100 + 14)
#define VAR_OLIVINE_CITY_STATE                        (0x4100 + 15)
#define VAR_RAIKOU_EVENT                              (0x4100 + 16)
#define VAR_ROCKET_HIDEOUT_STATUE_1                   (0x4100 + 17)
#define VAR_ROCKET_HIDEOUT_STATUE_2                   (0x4100 + 18)
#define VAR_ROCKET_HIDEOUT_STATUE_3                   (0x4100 + 19)
#define VAR_ROCKET_HIDEOUT_STATUE_4                   (0x4100 + 20)
#define VAR_ROCKET_HIDEOUT_STATUE_5                   (0x4100 + 21)
#define VAR_ROUTE27_BAOBA_CALL                        (0x4100 + 22)
#define VAR_ROUTE27_STATE                             (0x4100 + 23)
#define VAR_SAFARI_ZONE_GATE_STATE                    (0x4100 + 24)
#define VAR_SLOWPOKE_TAIL                             (0x4100 + 25)
#define VAR_SPROUT_TOWER                              (0x4100 + 26)
#define VAR_SSAQUA_STATE                              (0x4100 + 27)
#define VAR_SUICUNE_ENCOUNTERS                        (0x4100 + 28)
#define VAR_SUICUNE_EVENT                             (0x4100 + 29)
#define VAR_TOHJO_FALLS_GIOVANNI_STATE                (0x4100 + 30)
#define VAR_VIOLET_CITY_STATE                         (0x4100 + 31)

// Johto flags
#define FLAG_AMPHAROS_HEALED                                         (0x0500 + 0)
#define FLAG_DAY_POKEMON                                             (0x0500 + 1)
#define FLAG_DEFEATED_RAIKOU                                         (0x0500 + 2)
#define FLAG_DEFEATED_SUICUNE                                        (0x0500 + 3)
#define FLAG_DEFEATED_VIRIDIAN_GYM                                   (0x0500 + 4)
#define FLAG_DELIVERED_EGG                                           (0x0500 + 5)
#define FLAG_ENABLE_BAOBA_MATCH_CALL                                 (0x0500 + 6)
#define FLAG_ENABLE_RADIO                                            (0x0500 + 7)
#define FLAG_HIDE_AZALEA_ARIADOS_LEFT                                (0x0500 + 8)
#define FLAG_HIDE_AZALEA_ARIADOS_MID                                 (0x0500 + 9)
#define FLAG_HIDE_AZALEA_ARIADOS_RIGHT                               (0x0500 + 10)
#define FLAG_HIDE_AZALEA_TOWN_CUT_MASTER                             (0x0500 + 11)
#define FLAG_HIDE_AZALEA_TOWN_FARFETCHD                              (0x0500 + 12)
#define FLAG_HIDE_AZALEA_TOWN_KURT                                   (0x0500 + 13)
#define FLAG_HIDE_AZALEA_TOWN_ROCKETS                                (0x0500 + 14)
#define FLAG_HIDE_AZALEA_TOWN_SILVER                                 (0x0500 + 15)
#define FLAG_HIDE_AZALEA_TOWN_SLOWPOKE                               (0x0500 + 16)
#define FLAG_HIDE_AZALEA_TOWN_WELL_ROCKET                            (0x0500 + 17)
#define FLAG_HIDE_BELLCHIME_MORTY                                    (0x0500 + 18)
#define FLAG_HIDE_BUG_CONTEST_ATTENDANT_SIDE                         (0x0500 + 19)
#define FLAG_HIDE_BURNED_TOWER_B1F_EUSINE                            (0x0500 + 20)
#define FLAG_HIDE_BURNED_TOWER_BEASTS                                (0x0500 + 21)
#define FLAG_HIDE_BURNED_TOWER_NPCS                                  (0x0500 + 22)
#define FLAG_HIDE_CAFE_JASMINE                                       (0x0500 + 23)
#define FLAG_HIDE_CHERRYGROVE_GUIDE_GENT_HOUSE                       (0x0500 + 24)
#define FLAG_HIDE_CHIKORITABALL                                      (0x0500 + 25)
#define FLAG_HIDE_CIANWOOD_EUSINE                                    (0x0500 + 26)
#define FLAG_HIDE_CIANWOOD_SUICUNE                                   (0x0500 + 27)
#define FLAG_HIDE_CYNDAQUILBALL                                      (0x0500 + 28)
#define FLAG_HIDE_DEN_CLAIR                                          (0x0500 + 29)
#define FLAG_HIDE_DEPTSTORE_WHITNEY                                  (0x0500 + 30)
#define FLAG_HIDE_DRAGONS_DEN_CAVERN_CLAIR                           (0x0500 + 31)
#define FLAG_HIDE_DRAGONS_DEN_CAVERN_LANCE                           (0x0500 + 32)
#define FLAG_HIDE_DRAGONS_DEN_CAVERN_SILVER                          (0x0500 + 33)
#define FLAG_HIDE_DRAGONS_DEN_SHRINE_CLAIR                           (0x0500 + 34)
#define FLAG_HIDE_ECRUTEAK_BILL                                      (0x0500 + 35)
#define FLAG_HIDE_ECRUTEAK_CITY_SAGE                                 (0x0500 + 36)
#define FLAG_HIDE_ECRUTEAK_CITY_THEATER_KIMONOS                      (0x0500 + 37)
#define FLAG_HIDE_ECRUTEAK_CITY_THEATER_NPCS                         (0x0500 + 38)
#define FLAG_HIDE_ECRUTEAK_CITY_THEATER_ZUKI                         (0x0500 + 39)
#define FLAG_HIDE_ECRUTEAK_ROCKET                                    (0x0500 + 40)
#define FLAG_HIDE_ECRUTEAK_SILVER                                    (0x0500 + 41)
#define FLAG_HIDE_GOLDENROD_BEAUTY                                   (0x0500 + 42)
#define FLAG_HIDE_GOLDENROD_BILL                                     (0x0500 + 43)
#define FLAG_HIDE_GOLDENROD_NPCS                                     (0x0500 + 44)
#define FLAG_HIDE_GOLDENROD_RADIOTOWER_DIRECTOR                      (0x0500 + 45)
#define FLAG_HIDE_GOLDENROD_RADIOTOWER_DIRECTOR_2                    (0x0500 + 46)
#define FLAG_HIDE_GOLDENROD_RADIOTOWER_PETREL                        (0x0500 + 47)
#define FLAG_HIDE_GOLDENROD_ROCKETS                                  (0x0500 + 48)
#define FLAG_HIDE_GOLDENROD_ROCKET_SCOUT                             (0x0500 + 49)
#define FLAG_HIDE_GOLDENROD_UNDERGROUND_KIMONO                       (0x0500 + 50)
#define FLAG_HIDE_GOLDENROD_UNDERGROUND_SILVER                       (0x0500 + 51)
#define FLAG_HIDE_GUIDE_GENT_CHERRYGROVE                             (0x0500 + 52)
#define FLAG_HIDE_ICE_PATH_KIMONO                                    (0x0500 + 53)
#define FLAG_HIDE_ILEX_FOREST_APPRENTICE                             (0x0500 + 54)
#define FLAG_HIDE_ILEX_FOREST_FARFETCHD_1                            (0x0500 + 55)
#define FLAG_HIDE_ILEX_FOREST_FARFETCHD_2                            (0x0500 + 56)
#define FLAG_HIDE_ILEX_FOREST_FARFETCHD_3                            (0x0500 + 57)
#define FLAG_HIDE_ILEX_FOREST_FARFETCHD_4                            (0x0500 + 58)
#define FLAG_HIDE_ILEX_FOREST_KIMONO                                 (0x0500 + 59)
#define FLAG_HIDE_ILEX_FOREST_MASTER                                 (0x0500 + 60)
#define FLAG_HIDE_ILEX_FOREST_SECOND_CELEBI                          (0x0500 + 61)
#define FLAG_HIDE_JOHTO_GYM_LEADERS                                  (0x0500 + 62)
#define FLAG_HIDE_KURT_1                                             (0x0500 + 63)
#define FLAG_HIDE_KURT_2                                             (0x0500 + 64)
#define FLAG_HIDE_LAB_POLICEMAN                                      (0x0500 + 65)
#define FLAG_HIDE_LAKE_OF_RAGE_GYARADOS                              (0x0500 + 66)
#define FLAG_HIDE_LAKE_OF_RAGE_LANCE                                 (0x0500 + 67)
#define FLAG_HIDE_LAKE_PRYCE                                         (0x0500 + 68)
#define FLAG_HIDE_LIGHTHOUSE_JASMINE                                 (0x0500 + 69)
#define FLAG_HIDE_MAHOGANY_COP                                       (0x0500 + 70)
#define FLAG_HIDE_MAHOGANY_ROCKETS                                   (0x0500 + 71)
#define FLAG_HIDE_MAHOGANY_TOWN_FATMAN                               (0x0500 + 72)
#define FLAG_HIDE_MAHOGANY_TOWN_SHOP_NPCS                            (0x0500 + 73)
#define FLAG_HIDE_MOMS_FRIEND                                        (0x0500 + 74)
#define FLAG_HIDE_MOMS_FRIEND2                                       (0x0500 + 75)
#define FLAG_HIDE_MRPOKEMON                                          (0x0500 + 76)
#define FLAG_HIDE_MTSILVER_RED                                       (0x0500 + 77)
#define FLAG_HIDE_NEWBARKTOWN_LAB_AIDE                               (0x0500 + 78)
#define FLAG_HIDE_OLIVINE_CITY_GYM_JASMINE                           (0x0500 + 79)
#define FLAG_HIDE_OLIVINE_PORT_OAK                                   (0x0500 + 80)
#define FLAG_HIDE_OLIVINE_SABRINA                                    (0x0500 + 81)
#define FLAG_HIDE_OLIVINE_SILVER                                     (0x0500 + 82)
#define FLAG_HIDE_RAYQUAZA                                           (0x0500 + 83)
#define FLAG_HIDE_ROCKETHIDEOUT2_ARIANA_AND_GRUNT                    (0x0500 + 84)
#define FLAG_HIDE_ROCKETHIDEOUT2_LANCE_DRAGONITE                     (0x0500 + 85)
#define FLAG_HIDE_ROCKETHIDEOUT2_MURKROWGATE                         (0x0500 + 86)
#define FLAG_HIDE_ROCKETHIDEOUT2_MURKROWSTAIRS                       (0x0500 + 87)
#define FLAG_HIDE_ROCKETHIDEOUT3_GIOVANNI                            (0x0500 + 88)
#define FLAG_HIDE_ROCKETHIDEOUT3_LANCE_DRAGONITE                     (0x0500 + 89)
#define FLAG_HIDE_ROCKETHIDEOUT3_MURKROW                             (0x0500 + 90)
#define FLAG_HIDE_ROCKETHIDEOUT3_MURKROWSTAIRS                       (0x0500 + 91)
#define FLAG_HIDE_ROCKETHIDEOUT3_PETREL                              (0x0500 + 92)
#define FLAG_HIDE_ROCKETHIDEOUT3_SILVER                              (0x0500 + 93)
#define FLAG_HIDE_ROCKETHIDEOUT_ELECTRODE1                           (0x0500 + 94)
#define FLAG_HIDE_ROCKETHIDEOUT_ELECTRODE2                           (0x0500 + 95)
#define FLAG_HIDE_ROCKETHIDEOUT_ELECTRODE3                           (0x0500 + 96)
#define FLAG_HIDE_ROCKETHIDEOUT_ROCKETS                              (0x0500 + 97)
#define FLAG_HIDE_ROCKET_GOLDENROD_RADIOTOWER_1                      (0x0500 + 98)
#define FLAG_HIDE_ROUTE22_JANINE                                     (0x0500 + 99)
#define FLAG_HIDE_ROUTE39_SHADOW                                     (0x0500 + 100)
#define FLAG_HIDE_ROUTE42_EUSINE                                     (0x0500 + 101)
#define FLAG_HIDE_ROUTE42_SUICUNE                                    (0x0500 + 102)
#define FLAG_HIDE_ROUTE_30_NPCS                                      (0x0500 + 103)
#define FLAG_HIDE_SILVER_CHERRYGROVE                                 (0x0500 + 104)
#define FLAG_HIDE_SILVER_NEWBARKTOWN                                 (0x0500 + 105)
#define FLAG_HIDE_SLOWPOKE_WELL_KURT                                 (0x0500 + 106)
#define FLAG_HIDE_SPROUT_TOWER_SILVER                                (0x0500 + 107)
#define FLAG_HIDE_SSAQUA_1F_GRANDPA                                  (0x0500 + 108)
#define FLAG_HIDE_SSAQUA_CAPTAINS_ROOM_GRANDDAUGHTER                 (0x0500 + 109)
#define FLAG_HIDE_SSAQUA_ROOM_SSE_GRANDDAUGHTER                      (0x0500 + 110)
#define FLAG_HIDE_SSAQUA_SAILOR                                      (0x0500 + 111)
#define FLAG_HIDE_SUDOWOODO                                          (0x0500 + 112)
#define FLAG_HIDE_TIN_TOWER_KIMONO_GIRLS                             (0x0500 + 113)
#define FLAG_HIDE_TOHJO_GIOVANNI                                     (0x0500 + 114)
#define FLAG_HIDE_TOTODILEBALL                                       (0x0500 + 115)
#define FLAG_HIDE_TRAINER_SCHOOL_EARL                                (0x0500 + 116)
#define FLAG_HIDE_UNION_CAVE_LAPRAS                                  (0x0500 + 117)
#define FLAG_HIDE_VICTORY_ROAD_SILVER                                (0x0500 + 118)
#define FLAG_HIDE_VIOLET_CITY_AIDE                                   (0x0500 + 119)
#define FLAG_HIDE_VIOLET_CITY_EARL                                   (0x0500 + 120)
#define FLAG_HIDE_VIOLET_CITY_KIMONO_GIRL                            (0x0500 + 121)
#define FLAG_HIDE_WHIRL_ISLANDS_KIMONO_GIRLS                         (0x0500 + 122)
#define FLAG_HIDE_WHIRL_ISLANDS_TENTACRUEL                           (0x0500 + 123)
#define FLAG_INDIGOJUNCTION_HIDE_KANTO_GUARD                         (0x0500 + 124)
#define FLAG_INDIGOJUNCTION_HIDE_SILVER_GUARD                        (0x0500 + 125)
#define FLAG_ITEM_BELLCHIME_BIG_MUSHROOM                             (0x0500 + 126)
#define FLAG_ITEM_BURNED_TOWER_1F_ETHER                              (0x0500 + 127)
#define FLAG_ITEM_BURNED_TOWER_1F_HP_UP                              (0x0500 + 128)
#define FLAG_ITEM_BURNED_TOWER_B1F_TM_TAUNT                          (0x0500 + 129)
#define FLAG_ITEM_BURNED_TOWER_B1F_ULTRA_BALL                        (0x0500 + 130)
#define FLAG_ITEM_DARKCAVE1_ELIXIR                                   (0x0500 + 131)
#define FLAG_ITEM_DARKCAVE1_MAX_REVIVE                               (0x0500 + 132)
#define FLAG_ITEM_DARKCAVE1_POTION                                   (0x0500 + 133)
#define FLAG_ITEM_DARKCAVE1_REVIVE                                   (0x0500 + 134)
#define FLAG_ITEM_DARKCAVE2_BLACK_FLUTE                              (0x0500 + 135)
#define FLAG_ITEM_DARKCAVE2_STAR_PIECE                               (0x0500 + 136)
#define FLAG_ITEM_DOME_FOSSIL                                        (0x0500 + 137)
#define FLAG_ITEM_DRAGONSDEN2_DRAGON_FANG                            (0x0500 + 138)
#define FLAG_ITEM_DRAGONSDEN2_MAX_POTION                             (0x0500 + 139)
#define FLAG_ITEM_DRAGONSDEN2_PP_MAX                                 (0x0500 + 140)
#define FLAG_ITEM_ECRUTEAK_RARE_CANDY                                (0x0500 + 141)
#define FLAG_ITEM_GOLDENROD_UNDERGROUND_AMULET_COIN                  (0x0500 + 142)
#define FLAG_ITEM_GOLDENROD_UNDERGROUND_ANTIDOTE                     (0x0500 + 143)
#define FLAG_ITEM_GOLDENROD_UNDERGROUND_COIN_CASE                    (0x0500 + 144)
#define FLAG_ITEM_GOLDENROD_UNDERGROUND_ETHER                        (0x0500 + 145)
#define FLAG_ITEM_GOLDENROD_UNDERGROUND_EXP_SHARE                    (0x0500 + 146)
#define FLAG_ITEM_GOLDENROD_UNDERGROUND_MAX_ETHER                    (0x0500 + 147)
#define FLAG_ITEM_GOLDENROD_UNDERGROUND_MAX_POTION                   (0x0500 + 148)
#define FLAG_ITEM_GOLDENROD_UNDERGROUND_PARALYZE_HEAL                (0x0500 + 149)
#define FLAG_ITEM_GOLDENROD_UNDERGROUND_REVIVE                       (0x0500 + 150)
#define FLAG_ITEM_GOLDENROD_UNDERGROUND_SMOKE_BALL                   (0x0500 + 151)
#define FLAG_ITEM_GOLDENROD_UNDERGROUND_SUPER_POTION                 (0x0500 + 152)
#define FLAG_ITEM_GOLDENROD_UNDERGROUND_TM_CALM_MIND                 (0x0500 + 153)
#define FLAG_ITEM_GOLDENROD_UNDERGROUND_ULTRA_BALL                   (0x0500 + 154)
#define FLAG_ITEM_GOLDENROD_UNDERGROUND_ULTRA_BALL2                  (0x0500 + 155)
#define FLAG_ITEM_GS_BALL                                            (0x0500 + 156)
#define FLAG_ITEM_HELIX_FOSSIL                                       (0x0500 + 157)
#define FLAG_ITEM_ICEPATH1_HM_WATERFALL                              (0x0500 + 158)
#define FLAG_ITEM_ICEPATH1_PP_UP                                     (0x0500 + 159)
#define FLAG_ITEM_ICEPATH1_PROTEIN                                   (0x0500 + 160)
#define FLAG_ITEM_ICEPATH2_IRON                                      (0x0500 + 161)
#define FLAG_ITEM_ICEPATH2_REVIVE                                    (0x0500 + 162)
#define FLAG_ITEM_ICEPATH3_CARBOS                                    (0x0500 + 163)
#define FLAG_ITEM_ICEPATH3_FULL_HEAL                                 (0x0500 + 164)
#define FLAG_ITEM_ICEPATH3_MAX_POTION                                (0x0500 + 165)
#define FLAG_ITEM_ICEPATH3_NEVER_MELT_ICE                            (0x0500 + 166)
#define FLAG_ITEM_ILEX_FOREST_ETHER                                  (0x0500 + 167)
#define FLAG_ITEM_ILEX_FOREST_FULL_HEAL                              (0x0500 + 168)
#define FLAG_ITEM_ILEX_FOREST_SUPER_POTION                           (0x0500 + 169)
#define FLAG_ITEM_ILEX_FOREST_TM_SUNNY_DAY                           (0x0500 + 170)
#define FLAG_ITEM_LAKEOFRAGE_FULL_RESTORE                            (0x0500 + 171)
#define FLAG_ITEM_LAKEOFRAGE_MAX_REVIVE                              (0x0500 + 172)
#define FLAG_ITEM_LAKEOFRAGE_RED_FLUTE                               (0x0500 + 173)
#define FLAG_ITEM_LIGHTHOUSE_ETHER                                   (0x0500 + 174)
#define FLAG_ITEM_LIGHTHOUSE_HYPER_POTION                            (0x0500 + 175)
#define FLAG_ITEM_LIGHTHOUSE_PROTEIN                                 (0x0500 + 176)
#define FLAG_ITEM_LIGHTHOUSE_RARE_CANDY                              (0x0500 + 177)
#define FLAG_ITEM_LUCKY_PUNCH                                        (0x0500 + 178)
#define FLAG_ITEM_MTMORTAR1_ELIXIR                                   (0x0500 + 179)
#define FLAG_ITEM_MTMORTAR1_REVIVE                                   (0x0500 + 180)
#define FLAG_ITEM_MTMORTAR2_ESCAPE_ROPE                              (0x0500 + 181)
#define FLAG_ITEM_MTMORTAR2_KINGS_ROCK                               (0x0500 + 182)
#define FLAG_ITEM_MTMORTAR2_MAX_POTION                               (0x0500 + 183)
#define FLAG_ITEM_MTMORTAR2_MAX_REPEL                                (0x0500 + 184)
#define FLAG_ITEM_MTMORTAR2_NUGGET                                   (0x0500 + 185)
#define FLAG_ITEM_MTMORTAR2_REVIVE                                   (0x0500 + 186)
#define FLAG_ITEM_MTMORTAR2_ULTRA_BALL                               (0x0500 + 187)
#define FLAG_ITEM_MTMORTAR3_DRAGON_SCALE                             (0x0500 + 188)
#define FLAG_ITEM_MTMORTAR3_ELIXIR                                   (0x0500 + 189)
#define FLAG_ITEM_MTMORTAR3_ETHER                                    (0x0500 + 190)
#define FLAG_ITEM_MTMORTAR3_IRON                                     (0x0500 + 191)
#define FLAG_ITEM_MTMORTAR3_MAX_REVIVE                               (0x0500 + 192)
#define FLAG_ITEM_MTMORTAR3_RARE_CANDY                               (0x0500 + 193)
#define FLAG_ITEM_MTMORTAR4_CARBOS                                   (0x0500 + 194)
#define FLAG_ITEM_MTMORTAR4_HYPER_POTION                             (0x0500 + 195)
#define FLAG_ITEM_MTMORTAR4_MAX_ETHER                                (0x0500 + 196)
#define FLAG_ITEM_MTMORTAR4_MAX_REVIVE                               (0x0500 + 197)
#define FLAG_ITEM_MTMORTAR4_PP_UP                                    (0x0500 + 198)
#define FLAG_ITEM_MTSILVER_DIREHIT                                   (0x0500 + 199)
#define FLAG_ITEM_MTSILVER_FULLRESTORE                               (0x0500 + 200)
#define FLAG_ITEM_MTSILVER_MAXPOTION                                 (0x0500 + 201)
#define FLAG_ITEM_MTSILVER_NERVERMELTICE                             (0x0500 + 202)
#define FLAG_ITEM_MTSILVER_RARECANDY                                 (0x0500 + 203)
#define FLAG_ITEM_MTSILVER_SPELL_TAG                                 (0x0500 + 204)
#define FLAG_ITEM_MTSILVER_ULTRABALL                                 (0x0500 + 205)
#define FLAG_ITEM_NATIONAL_PARK_SOOTHE_BELL                          (0x0500 + 206)
#define FLAG_ITEM_NATIONAL_PARK_TM_DIG                               (0x0500 + 207)
#define FLAG_ITEM_OLD_AMBER                                          (0x0500 + 208)
#define FLAG_ITEM_OLIVINE_TM_SHOCKWAVE                               (0x0500 + 209)
#define FLAG_ITEM_ROCKETHIDEOUT1_BIG_NUGGET                          (0x0500 + 210)
#define FLAG_ITEM_ROCKETHIDEOUT1_HYPER_POTION                        (0x0500 + 211)
#define FLAG_ITEM_ROCKETHIDEOUT1_REVIVE                              (0x0500 + 212)
#define FLAG_ITEM_ROCKETHIDEOUT2_TM_THIEF                            (0x0500 + 213)
#define FLAG_ITEM_ROCKETHIDEOUT3_FULL_HEAL                           (0x0500 + 214)
#define FLAG_ITEM_ROCKETHIDEOUT3_GUARD_SPEC                          (0x0500 + 215)
#define FLAG_ITEM_ROCKETHIDEOUT3_HYPER_POTION                        (0x0500 + 216)
#define FLAG_ITEM_ROCKETHIDEOUT3_ICE_HEAL                            (0x0500 + 217)
#define FLAG_ITEM_ROCKETHIDEOUT3_PROTEIN                             (0x0500 + 218)
#define FLAG_ITEM_ROUTE27_MOONSTONE                                  (0x0500 + 219)
#define FLAG_ITEM_ROUTE27_RARECANDY                                  (0x0500 + 220)
#define FLAG_ITEM_ROUTE27_REVIVE                                     (0x0500 + 221)
#define FLAG_ITEM_ROUTE27_SOLARBEAM                                  (0x0500 + 222)
#define FLAG_ITEM_ROUTE34_RARECANDY                                  (0x0500 + 223)
#define FLAG_ITEM_ROUTE34_SOFTSAND                                   (0x0500 + 224)
#define FLAG_ITEM_ROUTE34_SUPERPOTION                                (0x0500 + 225)
#define FLAG_ITEM_ROUTE35_BIG_NUGGET                                 (0x0500 + 226)
#define FLAG_ITEM_ROUTE35_PARALYZE_HEAL                              (0x0500 + 227)
#define FLAG_ITEM_ROUTE35_ROCK_TOMB                                  (0x0500 + 228)
#define FLAG_ITEM_ROUTE38_LAX_INCENSE                                (0x0500 + 229)
#define FLAG_ITEM_ROUTE39_NUGGET                                     (0x0500 + 230)
#define FLAG_ITEM_ROUTE39_TM_BRICK_BREAK                             (0x0500 + 231)
#define FLAG_ITEM_ROUTE42_MODEST_MINT                                (0x0500 + 232)
#define FLAG_ITEM_ROUTE42_SUPER_POTION                               (0x0500 + 233)
#define FLAG_ITEM_ROUTE42_ULTRA_BALL                                 (0x0500 + 234)
#define FLAG_ITEM_ROUTE43_MAX_ETHER                                  (0x0500 + 235)
#define FLAG_ITEM_ROUTE44_ELIXIR                                     (0x0500 + 236)
#define FLAG_ITEM_ROUTE44_MAX_REPEL                                  (0x0500 + 237)
#define FLAG_ITEM_ROUTE44_ULTRA_BALL                                 (0x0500 + 238)
#define FLAG_ITEM_ROUTE45_ELIXIR                                     (0x0500 + 239)
#define FLAG_ITEM_ROUTE45_FULL_HEAL                                  (0x0500 + 240)
#define FLAG_ITEM_ROUTE45_MAX_POTION                                 (0x0500 + 241)
#define FLAG_ITEM_ROUTE45_NUGGET                                     (0x0500 + 242)
#define FLAG_ITEM_ROUTE46_REVIVE                                     (0x0500 + 243)
#define FLAG_ITEM_ROUTE47_PEARL                                      (0x0500 + 244)
#define FLAG_ITEM_ROUTE47_REVIVE                                     (0x0500 + 245)
#define FLAG_ITEM_ROUTE47_STARDUST                                   (0x0500 + 246)
#define FLAG_ITEM_ROUTE47_WHITE_FLUTE                                (0x0500 + 247)
#define FLAG_ITEM_ROUTE_29_POTION                                    (0x0500 + 248)
#define FLAG_ITEM_ROUTE_31_ANTIDOE                                   (0x0500 + 249)
#define FLAG_ITEM_ROUTE_31_POKEBALL                                  (0x0500 + 250)
#define FLAG_ITEM_ROUTE_32_GREATBALL                                 (0x0500 + 251)
#define FLAG_ITEM_ROUTE_32_GREATBALL2                                (0x0500 + 252)
#define FLAG_ITEM_ROUTE_32_POTION                                    (0x0500 + 253)
#define FLAG_ITEM_ROUTE_32_SUPERPOTION                               (0x0500 + 254)
#define FLAG_ITEM_RUINSOFALPH_CHARCOAL                               (0x0500 + 255)
#define FLAG_ITEM_RUINSOFALPH_ENERGY_POWDER                          (0x0500 + 256)
#define FLAG_ITEM_RUINSOFALPH_ENERGY_ROOT                            (0x0500 + 257)
#define FLAG_ITEM_RUINSOFALPH_HEAL_POWDER_1                          (0x0500 + 258)
#define FLAG_ITEM_RUINSOFALPH_HEAL_POWDER_2                          (0x0500 + 259)
#define FLAG_ITEM_RUINSOFALPH_LUM_BERRY_1                            (0x0500 + 260)
#define FLAG_ITEM_RUINSOFALPH_LUM_BERRY_2                            (0x0500 + 261)
#define FLAG_ITEM_RUINSOFALPH_MAX_REVIVE_1                           (0x0500 + 262)
#define FLAG_ITEM_RUINSOFALPH_MOON_STONE                             (0x0500 + 263)
#define FLAG_ITEM_RUINSOFALPH_ORAN_BERRY                             (0x0500 + 264)
#define FLAG_ITEM_RUINSOFALPH_PECHA_BERRY                            (0x0500 + 265)
#define FLAG_ITEM_RUINSOFALPH_SACRED_ASH                             (0x0500 + 266)
#define FLAG_ITEM_RUINSOFALPH_SITRUS_BERRY_2                         (0x0500 + 267)
#define FLAG_ITEM_RUINSOFALPH_STARDUST                               (0x0500 + 268)
#define FLAG_ITEM_RUINSOFALPH_STAR_PIECE                             (0x0500 + 269)
#define FLAG_ITEM_RUINSOFALPH_WATER_STONE                            (0x0500 + 270)
#define FLAG_ITEM_SLOWPOKE_WELL_FULL_HEAL                            (0x0500 + 271)
#define FLAG_ITEM_SLOWPOKE_WELL_GREAT_BALL                           (0x0500 + 272)
#define FLAG_ITEM_SLOWPOKE_WELL_KINGS_ROCK                           (0x0500 + 273)
#define FLAG_ITEM_SLOWPOKE_WELL_SUPER_POTION                         (0x0500 + 274)
#define FLAG_ITEM_SLOWPOKE_WELL_SUPER_POTION2                        (0x0500 + 275)
#define FLAG_ITEM_SPROUT_TOWER_ESCAPE_ROPE                           (0x0500 + 276)
#define FLAG_ITEM_SPROUT_TOWER_PARALYZE_HEAL                         (0x0500 + 277)
#define FLAG_ITEM_SPROUT_TOWER_POTION                                (0x0500 + 278)
#define FLAG_ITEM_SPROUT_TOWER_X_DEFEND                              (0x0500 + 279)
#define FLAG_ITEM_TIN_TOWER_3F_FULL_HEAL                             (0x0500 + 280)
#define FLAG_ITEM_TIN_TOWER_4F_ESCAPE_ROPE                           (0x0500 + 281)
#define FLAG_ITEM_TIN_TOWER_4F_MAX_POTION                            (0x0500 + 282)
#define FLAG_ITEM_TIN_TOWER_4F_ULTRA_BALL                            (0x0500 + 283)
#define FLAG_ITEM_TIN_TOWER_5F_CARBOS                                (0x0500 + 284)
#define FLAG_ITEM_TIN_TOWER_5F_MAX_POTION                            (0x0500 + 285)
#define FLAG_ITEM_TIN_TOWER_5F_RARE_CANDY                            (0x0500 + 286)
#define FLAG_ITEM_TIN_TOWER_7F_MAX_REVIVE                            (0x0500 + 287)
#define FLAG_ITEM_TIN_TOWER_8F_BIG_NUGGET                            (0x0500 + 288)
#define FLAG_ITEM_TIN_TOWER_8F_FULL_RESTORE                          (0x0500 + 289)
#define FLAG_ITEM_TIN_TOWER_8F_MAX_ELIXIR                            (0x0500 + 290)
#define FLAG_ITEM_TOHJOFALLS_HEART_SCALE                             (0x0500 + 291)
#define FLAG_ITEM_UNION_CAVE_AWAKENING                               (0x0500 + 292)
#define FLAG_ITEM_UNION_CAVE_ETHER                                   (0x0500 + 293)
#define FLAG_ITEM_UNION_CAVE_GREAT_BALL                              (0x0500 + 294)
#define FLAG_ITEM_UNION_CAVE_HYPERPOTION                             (0x0500 + 295)
#define FLAG_ITEM_UNION_CAVE_MAXREVIVE                               (0x0500 + 296)
#define FLAG_ITEM_UNION_CAVE_POTION                                  (0x0500 + 297)
#define FLAG_ITEM_UNION_CAVE_SECRET_POWER                            (0x0500 + 298)
#define FLAG_ITEM_UNION_CAVE_X_ATTACK                                (0x0500 + 299)
#define FLAG_ITEM_UNION_CAVE_X_DEFEND                                (0x0500 + 300)
#define FLAG_ITEM_VICTORYROAD1_FULL_HEAL                             (0x0500 + 301)
#define FLAG_ITEM_VICTORYROAD1_MAX_REVIVE                            (0x0500 + 302)
#define FLAG_ITEM_VICTORYROAD1_POTION                                (0x0500 + 303)
#define FLAG_ITEM_VICTORYROAD2_FULL_RESTORE                          (0x0500 + 304)
#define FLAG_ITEM_VICTORYROAD2_HP_UP                                 (0x0500 + 305)
#define FLAG_ITEM_VICTORYROAD2_MAX_REVIVE                            (0x0500 + 306)
#define FLAG_ITEM_VICTORYROAD3_MAX_ETHER                             (0x0500 + 307)
#define FLAG_ITEM_VICTORYROAD3_RARE_CANDY                            (0x0500 + 308)
#define FLAG_ITEM_VICTORYROAD3_ULTRA_BALL                            (0x0500 + 309)
#define FLAG_ITEM_VIOLET_CITY_HYPER_POTION                           (0x0500 + 310)
#define FLAG_ITEM_VIOLET_CITY_PECHA_BERRY                            (0x0500 + 311)
#define FLAG_ITEM_VIOLET_CITY_RARE_CANDY                             (0x0500 + 312)
#define FLAG_ITEM_WHIRL_ISLANDS_1F_FULL_RESTORE                      (0x0500 + 313)
#define FLAG_ITEM_WHIRL_ISLANDS_1F_GUARD_SPEC                        (0x0500 + 314)
#define FLAG_ITEM_WHIRL_ISLANDS_1F_RARE_CANDY                        (0x0500 + 315)
#define FLAG_ITEM_WHIRL_ISLANDS_1F_ULTRA_BALL                        (0x0500 + 316)
#define FLAG_ITEM_WHIRL_ISLANDS_B1F_FULL_RESTORE                     (0x0500 + 317)
#define FLAG_ITEM_WHIRL_ISLANDS_B1F_MAX_REVIVE                       (0x0500 + 318)
#define FLAG_ITEM_WHIRL_ISLANDS_B1F_PP_MAX                           (0x0500 + 319)
#define FLAG_ITEM_WHIRL_ISLANDS_B2F_BIG_NUGGET                       (0x0500 + 320)
#define FLAG_ITEM_WHIRL_ISLANDS_B2F_CALCIUM                          (0x0500 + 321)
#define FLAG_ITEM_WHIRL_ISLANDS_B2F_CARBOS                           (0x0500 + 322)
#define FLAG_ITEM_WHIRL_ISLANDS_B2F_ESCAPE_ROPE                      (0x0500 + 323)
#define FLAG_ITEM_WHIRL_ISLANDS_B2F_FULL_RESTORE                     (0x0500 + 324)
#define FLAG_MINTS_CLERK                                             (0x0500 + 325)
#define FLAG_MOM_VISITED                                             (0x0500 + 326)
#define FLAG_NIGHT_POKEMON                                           (0x0500 + 327)
#define FLAG_RAIKOU_BATTLE_1                                         (0x0500 + 328)
#define FLAG_RAIKOU_BATTLE_2                                         (0x0500 + 329)
#define FLAG_SAFARI_ZONE_EAST_EXPANSION                              (0x0500 + 330)
#define FLAG_SAFARI_ZONE_WEST_EXPANSION                              (0x0500 + 331)
#define FLAG_SUICUNE_BATTLE_1                                        (0x0500 + 332)
#define FLAG_SUICUNE_BATTLE_2                                        (0x0500 + 333)

// Johto NPC sprite placeholders
#define OBJ_EVENT_GFX_ARCHER                          OBJ_EVENT_GFX_ROCKET_M
#define OBJ_EVENT_GFX_ARIANA                          OBJ_EVENT_GFX_ROCKET_F
#define OBJ_EVENT_GFX_ATTENDANT                       OBJ_EVENT_GFX_WOMAN_1
#define OBJ_EVENT_GFX_ATTENDANT_M                     OBJ_EVENT_GFX_MAN_1
#define OBJ_EVENT_GFX_BUGSY                           OBJ_EVENT_GFX_BOY_1
#define OBJ_EVENT_GFX_BURGLAR                         OBJ_EVENT_GFX_MAN_1
#define OBJ_EVENT_GFX_CHUCK                           OBJ_EVENT_GFX_MAN_1
#define OBJ_EVENT_GFX_CLAIR                           OBJ_EVENT_GFX_WOMAN_1
#define OBJ_EVENT_GFX_ENGINEER                        OBJ_EVENT_GFX_SCIENTIST_1
#define OBJ_EVENT_GFX_EUSINE                          OBJ_EVENT_GFX_MAN_1
#define OBJ_EVENT_GFX_FALKNER                         OBJ_EVENT_GFX_BOY_1
#define OBJ_EVENT_GFX_FIREBREATHER                    OBJ_EVENT_GFX_FAT_MAN
#define OBJ_EVENT_GFX_JANINE                          OBJ_EVENT_GFX_WOMAN_1
#define OBJ_EVENT_GFX_JASMINE                         OBJ_EVENT_GFX_WOMAN_1
#define OBJ_EVENT_GFX_JUGGLER                         OBJ_EVENT_GFX_MAN_1
#define OBJ_EVENT_GFX_KAREN                           OBJ_EVENT_GFX_WOMAN_1
#define OBJ_EVENT_GFX_KIMONO_GIRL                     OBJ_EVENT_GFX_WOMAN_1
#define OBJ_EVENT_GFX_KURT                            OBJ_EVENT_GFX_OLD_MAN
#define OBJ_EVENT_GFX_LEGENDARY_SHADOW                OBJ_EVENT_GFX_ITEM_BALL
#define OBJ_EVENT_GFX_MON_BASE                        OBJ_EVENT_GFX_ITEM_BALL
#define OBJ_EVENT_GFX_MORTY                           OBJ_EVENT_GFX_MAN_1
#define OBJ_EVENT_GFX_NURSE_CHANSEY                   OBJ_EVENT_GFX_WOMAN_1
#define OBJ_EVENT_GFX_PETREL                          OBJ_EVENT_GFX_ROCKET_M
#define OBJ_EVENT_GFX_PROF_ELM                        OBJ_EVENT_GFX_SCIENTIST_1
#define OBJ_EVENT_GFX_PROTON                          OBJ_EVENT_GFX_ROCKET_M
#define OBJ_EVENT_GFX_PRYCE                           OBJ_EVENT_GFX_OLD_MAN
#define OBJ_EVENT_GFX_SAGE                            OBJ_EVENT_GFX_OLD_MAN
#define OBJ_EVENT_GFX_SCIENTIST_F                     OBJ_EVENT_GFX_WOMAN_1
#define OBJ_EVENT_GFX_SCIENTIST_M                     OBJ_EVENT_GFX_SCIENTIST_1
#define OBJ_EVENT_GFX_SHINY_GYARADOS                  OBJ_EVENT_GFX_ITEM_BALL
// OBJ_EVENT_GFX_SILVER is now a real entry in event_objects.h (388)
#define OBJ_EVENT_GFX_SLOWPOKE_NO_TAIL                OBJ_EVENT_GFX_ITEM_BALL
#define OBJ_EVENT_GFX_SURGE                           OBJ_EVENT_GFX_MAN_1
#define OBJ_EVENT_GFX_TRAIN_FRONT                     OBJ_EVENT_GFX_ITEM_BALL
#define OBJ_EVENT_GFX_WHIRLPOOL                       OBJ_EVENT_GFX_ITEM_BALL
#define OBJ_EVENT_GFX_WHITNEY                         OBJ_EVENT_GFX_WOMAN_1
#define OBJ_EVENT_GFX_WILL                            OBJ_EVENT_GFX_MAN_1

// Johto berry tree IDs
#define BERRY_TREE_ASPEAR_1                           90
#define BERRY_TREE_ASPEAR_2                           91
#define BERRY_TREE_CHERI_1                            92
#define BERRY_TREE_CHERI_2                            93
#define BERRY_TREE_CHESTO_1                           94
#define BERRY_TREE_CHESTO_2                           95
#define BERRY_TREE_GREPA_1                            96
#define BERRY_TREE_HONDEW_1                           97
#define BERRY_TREE_KELPSY_1                           98
#define BERRY_TREE_LEPPA_1                            99
#define BERRY_TREE_LEPPA_2                            100
#define BERRY_TREE_LUM_1                              101
#define BERRY_TREE_ORAN_1                             102
#define BERRY_TREE_ORAN_2                             103
#define BERRY_TREE_PECHA_1                            104
#define BERRY_TREE_PECHA_2                            105
#define BERRY_TREE_PERSIM_1                           106
#define BERRY_TREE_PERSIM_2                           107
#define BERRY_TREE_POMEG_1                            108
#define BERRY_TREE_QUALOT_1                           109
#define BERRY_TREE_RAWST_1                            110
#define BERRY_TREE_RAWST_2                            111
#define BERRY_TREE_SITRUS_1                           112
#define BERRY_TREE_TAMATO_1                           113

// Johto movement types
#define MOVEMENT_TYPE_TOWER_BEAM MOVEMENT_TYPE_NONE

#endif // GUARD_CONSTANTS_JOHTO_CONSTANTS_H
