BlackthornCity_House3_MapScripts::
	.byte 0

@ Johto map scripts (imported from HnS, stubs)

BlackthornCity_MoveDeletersHouse_EventScript_MoveDeleter::
	msgbox BlackthornCity_MoveDeletersHouse_Text_MoveDeleter, MSGBOX_NPC
	end

BlackthornCity_MoveRelearnersHouse_EventScript_MoveRelearner::
	msgbox BlackthornCity_MoveRelearnersHouse_Text_MoveRelearner, MSGBOX_NPC
	end


BlackthornCity_MoveDeletersHouse_Text_MoveDeleter:
	.string "...$"

BlackthornCity_MoveRelearnersHouse_Text_MoveRelearner:
	.string "...$"
