Route40_MapScripts::
	.byte 0

@ Johto map scripts (imported from HnS, stubs)

Rotue40_EventScript_Monica::
	msgbox Rotue40_Text_Monica, MSGBOX_NPC
	end

Route40_EventScript_Elaine::
	msgbox Route40_Text_Elaine, MSGBOX_NPC
	end

Route40_EventScript_Paula::
	msgbox Route40_Text_Paula, MSGBOX_NPC
	end

Route40_EventScript_Randall::
	msgbox Route40_Text_Randall, MSGBOX_NPC
	end

Route40_EventScript_Simon::
	msgbox Route40_Text_Simon, MSGBOX_NPC
	end

Route40_EventScript_Woman1::
	msgbox Route40_Text_Woman1, MSGBOX_NPC
	end

Route40_EventScript_Youngster::
	msgbox Route40_Text_Youngster, MSGBOX_NPC
	end

Route40_Text_Youngster:
	.string "I want to catch every kind of\n"
	.string "POKeMON in JOHTO!$"


Rotue40_Text_Monica:
	.string "...$"

Route40_Text_Elaine:
	.string "...$"

Route40_Text_Paula:
	.string "...$"

Route40_Text_Randall:
	.string "...$"

Route40_Text_Simon:
	.string "...$"

Route40_Text_Woman1:
	.string "Be careful out there! Wild\nPOKeMON can be dangerous!$"
