CherrygroveCity_House1_MapScripts::
	.byte 0

@ Johto map scripts (imported from HnS, stubs)

CherrygroveCity_House1_EventScript_Baldingman::
	msgbox CherrygroveCity_House1_Text_Baldingman, MSGBOX_NPC
	end

CherrygroveCity_House1_EventScript_Kid::
	msgbox CherrygroveCity_House1_Text_Kid, MSGBOX_NPC
	end

CherrygroveCity_House1_Text_Baldingman:
	.string "When I was young, I traveled\n"
	.string "across JOHTO with my POKeMON.\pThose were the days...$"

CherrygroveCity_House1_Text_Kid:
	.string "I'm going to get my first\n"
	.string "POKeMON soon! I can't wait!$"

