SproutTower_1F_MapScripts::
	.byte 0

@ Johto map scripts (imported from HnS, stubs)

SproutTower_1F_EventScript_Granny::
	msgbox SproutTower_1F_Text_Granny, MSGBOX_NPC
	end

SproutTower_1F_EventScript_ItemParalyzeHeal::
	msgbox SproutTower_1F_Text_ItemParalyzeHeal, MSGBOX_NPC
	end

SproutTower_1F_EventScript_Sage1::
	msgbox SproutTower_1F_Text_Sage1, MSGBOX_NPC
	end

SproutTower_1F_EventScript_Sage2::
	msgbox SproutTower_1F_Text_Sage2, MSGBOX_NPC
	end

SproutTower_1F_EventScript_SageChow::
	msgbox SproutTower_1F_Text_SageChow, MSGBOX_NPC
	end

SproutTower_1F_EventScript_Teacher::
	msgbox SproutTower_1F_Text_Teacher, MSGBOX_NPC
	end

SproutTower_2F_EventScript_Statue::
	msgbox SproutTower_2F_Text_Statue, MSGBOX_SIGN
	end


SproutTower_1F_Text_Granny:
	.string "Would you like some tea, dear?\nYou look tired from traveling.$"

SproutTower_1F_Text_ItemParalyzeHeal:
	.string "...$"

SproutTower_1F_Text_Sage1:
	.string "Wisdom comes with patience\nand understanding.$"

SproutTower_1F_Text_Sage2:
	.string "Wisdom comes with patience\nand understanding.$"

SproutTower_1F_Text_SageChow:
	.string "Wisdom comes with patience\nand understanding.$"

SproutTower_1F_Text_Teacher:
	.string "Knowledge is the key to\nbecoming a great TRAINER!$"

SproutTower_2F_Text_Statue:
	.string "SproutTower 1F$"
