EcruteakCity_House1_MapScripts::
	.byte 0

@ Johto map scripts (imported from HnS, stubs)

EcruteakCity_House1_EventScript_Gramps::
	msgbox EcruteakCity_House1_Text_Gramps, MSGBOX_NPC
	end

EcruteakCity_House1_EventScript_Youngster::
	msgbox EcruteakCity_House1_Text_Youngster, MSGBOX_NPC
	end

EcruteakCity_House1_Text_Gramps:
	.string "I've lived in JOHTO my whole life.\n"
	.string "It's a beautiful region.\pTake your time and enjoy\n"
	.string "the journey, youngster.$"

EcruteakCity_House1_Text_Youngster:
	.string "I want to catch every kind of\n"
	.string "POKeMON in JOHTO!$"

