Route41_MapScripts::
	.byte 0

@ Johto map scripts (imported from HnS, stubs)

Route41_EventScript_Berke::
	msgbox Route41_Text_Berke, MSGBOX_NPC
	end

Route41_EventScript_Charlie::
	msgbox Route41_Text_Charlie, MSGBOX_NPC
	end

Route41_EventScript_Denise::
	msgbox Route41_Text_Denise, MSGBOX_NPC
	end

Route41_EventScript_George::
	msgbox Route41_Text_George, MSGBOX_NPC
	end

Route41_EventScript_Kara::
	msgbox Route41_Text_Kara, MSGBOX_NPC
	end

Route41_EventScript_Kaylee::
	msgbox Route41_Text_Kaylee, MSGBOX_NPC
	end

Route41_EventScript_Kirk::
	msgbox Route41_Text_Kirk, MSGBOX_NPC
	end

Route41_EventScript_Mathew::
	msgbox Route41_Text_Mathew, MSGBOX_NPC
	end

Route41_EventScript_Susie::
	msgbox Route41_Text_Susie, MSGBOX_NPC
	end

Route41_EventScript_Tentacruel1::
	msgbox Route41_Text_Tentacruel1, MSGBOX_NPC
	end

Route41_EventScript_Tentacruel2::
	msgbox Route41_Text_Tentacruel2, MSGBOX_NPC
	end

Route41_EventScript_Tentacruel3::
	msgbox Route41_Text_Tentacruel3, MSGBOX_NPC
	end

Route41_EventScript_Tentacruel4::
	msgbox Route41_Text_Tentacruel4, MSGBOX_NPC
	end

Route41_EventScript_Wendy::
	msgbox Route41_Text_Wendy, MSGBOX_NPC
	end


Route41_Text_Berke:
	.string "...$"

Route41_Text_Charlie:
	.string "...$"

Route41_Text_Denise:
	.string "...$"

Route41_Text_George:
	.string "...$"

Route41_Text_Kara:
	.string "...$"

Route41_Text_Kaylee:
	.string "...$"

Route41_Text_Kirk:
	.string "...$"

Route41_Text_Mathew:
	.string "...$"

Route41_Text_Susie:
	.string "...$"

Route41_Text_Tentacruel1:
	.string "...$"

Route41_Text_Tentacruel2:
	.string "...$"

Route41_Text_Tentacruel3:
	.string "...$"

Route41_Text_Tentacruel4:
	.string "...$"

Route41_Text_Wendy:
	.string "...$"
