SproutTower_3F_MapScripts::
	.byte 0

@ Johto map scripts (imported from HnS, stubs)

SproutTower_3F_EventScript_EscapeRope::
	msgbox SproutTower_3F_Text_EscapeRope, MSGBOX_NPC
	end

SproutTower_3F_EventScript_Painting::
	msgbox SproutTower_3F_Text_Painting, MSGBOX_NPC
	end

SproutTower_3F_EventScript_Potion::
	msgbox SproutTower_3F_Text_Potion, MSGBOX_NPC
	end

SproutTower_3F_EventScript_SageJin::
	msgbox SproutTower_3F_Text_SageJin, MSGBOX_NPC
	end

SproutTower_3F_EventScript_SageLi::
	msgbox SproutTower_3F_Text_SageLi, MSGBOX_NPC
	end

SproutTower_3F_EventScript_SageNeal::
	msgbox SproutTower_3F_Text_SageNeal, MSGBOX_NPC
	end

SproutTower_3F_EventScript_SageTroy::
	msgbox SproutTower_3F_Text_SageTroy, MSGBOX_NPC
	end

SproutTower_3F_EventScript_TriggerSceneLeft::
	return

SproutTower_3F_EventScript_TriggerSceneRight::
	return


SproutTower_3F_Text_EscapeRope:
	.string "...$"

SproutTower_3F_Text_Painting:
	.string "...$"

SproutTower_3F_Text_Potion:
	.string "...$"

SproutTower_3F_Text_SageJin:
	.string "Wisdom comes with patience\nand understanding.$"

SproutTower_3F_Text_SageLi:
	.string "Wisdom comes with patience\nand understanding.$"

SproutTower_3F_Text_SageNeal:
	.string "Wisdom comes with patience\nand understanding.$"

SproutTower_3F_Text_SageTroy:
	.string "Wisdom comes with patience\nand understanding.$"
