MahoganyTown_House1_MapScripts::
	.byte 0

@ Johto map scripts (imported from HnS, stubs)

MahoganyTown_House1_EventScript_BlackBelt::
	msgbox MahoganyTown_House1_Text_BlackBelt, MSGBOX_NPC
	end

MahoganyTown_House1_EventScript_Teacher::
	msgbox MahoganyTown_House1_Text_Teacher, MSGBOX_NPC
	end

MahoganyTown_House1_Text_BlackBelt:
	.string "Hiyaah! Train your body and\n"
	.string "your POKeMON will follow!$"


MahoganyTown_House1_Text_Teacher:
	.string "Knowledge is the key to\nbecoming a great TRAINER!$"
