TinTower_1F_MapScripts::
	.byte 0

@ Johto map scripts (imported from HnS, stubs)

TinTower_1F_EventScript_SageA::
	msgbox TinTower_1F_Text_SageA, MSGBOX_NPC
	end

TinTower_1F_EventScript_SageB::
	msgbox TinTower_1F_Text_SageB, MSGBOX_NPC
	end

TinTower_1F_EventScript_SageC::
	msgbox TinTower_1F_Text_SageC, MSGBOX_NPC
	end


TinTower_1F_Text_SageA:
	.string "Wisdom comes with patience\nand understanding.$"

TinTower_1F_Text_SageB:
	.string "Wisdom comes with patience\nand understanding.$"

TinTower_1F_Text_SageC:
	.string "Wisdom comes with patience\nand understanding.$"
