NewBarkTown_House2_MapScripts::
	.byte 0

NewBarkTown_House2_EventScript_ElmsSon::
	msgbox NewBarkTown_House2_Text_ElmsSon, MSGBOX_NPC
	end

NewBarkTown_House2_EventScript_ElmsWife::
	msgbox NewBarkTown_House2_Text_ElmsWife, MSGBOX_NPC
	end

NewBarkTown_House2_Text_ElmsSon:
	.string "My dad works at the lab all\n"
	.string "day and all night!\p"
	.string "I want to be a POKeMON\n"
	.string "researcher too someday!$"

NewBarkTown_House2_Text_ElmsWife:
	.string "My husband is always at the\n"
	.string "lab. I sometimes bring him\l"
	.string "meals so he doesn't forget\l"
	.string "to eat.$"

