GoldenrodCity_DepartmentStore_5F_MapScripts::
	.byte 0

@ Johto map scripts (imported from HnS, stubs)

GoldenrodDeptStore5_EventScript_Girl::
	msgbox GoldenrodDeptStore5_Text_Girl, MSGBOX_NPC
	end

GoldenrodDeptStore5_EventScript_Lass::
	msgbox GoldenrodDeptStore5_Text_Lass, MSGBOX_NPC
	end

GoldenrodDeptStore5_EventScript_PokefanM::
	msgbox GoldenrodDeptStore5_Text_PokefanM, MSGBOX_NPC
	end

GoldenrodDeptStore5_EventScript_Receptionist::
	msgbox GoldenrodDeptStore5_Text_Receptionist, MSGBOX_NPC
	end

GoldenrodDeptStore5_EventScript_Sign::
	msgbox GoldenrodDeptStore5_Text_Sign, MSGBOX_SIGN
	end

GoldenrodDeptStore5_Text_Girl:
	.string "I heard some POKeMON only evolve\n"
	.string "when they really trust you!$"

GoldenrodDeptStore5_Text_Lass:
	.string "I love walking around town.\n"
	.string "The fresh air is wonderful!$"

GoldenrodDeptStore5_Text_PokefanM:
	.string "My POKeMON is the cutest!\n"
	.string "Don't you think so too?$"


GoldenrodDeptStore5_Text_Receptionist:
	.string "Welcome! How may I help you?$"

GoldenrodDeptStore5_Text_Sign:
	.string "GoldenrodCity DepartmentStore 5F$"
