BlackthornCity_MapScripts::
	.byte 0

BlackThornCity_EventScript_Sage::
	msgbox BlackThornCity_Text_Sage, MSGBOX_NPC
	end

BlackThornCity_Trigger_Sage::
	return

BlackthornCity_EventScript_BlackBelt::
	msgbox BlackthornCity_Text_BlackBelt, MSGBOX_NPC
	end

BlackthornCity_EventScript_CitySign::
	msgbox BlackthornCity_Text_CitySign, MSGBOX_SIGN
	end

BlackthornCity_EventScript_CoolTrainerF::
	msgbox BlackthornCity_Text_CoolTrainerF, MSGBOX_NPC
	end

BlackthornCity_EventScript_CoolTrainerF2::
	msgbox BlackthornCity_Text_CoolTrainerF2, MSGBOX_NPC
	end

BlackthornCity_EventScript_DragonsDenSign::
	msgbox BlackthornCity_Text_DragonsDenSign, MSGBOX_SIGN
	end

BlackthornCity_EventScript_GymBoy::
	msgbox BlackthornCity_Text_GymBoy, MSGBOX_NPC
	end

BlackthornCity_EventScript_GymSign::
	msgbox BlackthornCity_Text_GymSign, MSGBOX_SIGN
	end

BlackthornCity_EventScript_MoveHouseSign::
	msgbox BlackthornCity_Text_MoveHouseSign, MSGBOX_SIGN
	end

BlackthornCity_EventScript_Santos::
	msgbox BlackthornCity_Text_Santos, MSGBOX_NPC
	end

BlackthornCity_EventScript_Youngster::
	msgbox BlackthornCity_Text_Youngster, MSGBOX_NPC
	end

BlackThornCity_Text_Sage:
	.string "The path of the TRAINER is\n"
	.string "a journey of patience and\l"
	.string "understanding.$"

BlackthornCity_Text_BlackBelt:
	.string "Hiyaah! Train your body and\n"
	.string "your POKeMON will follow!$"

BlackthornCity_Text_CitySign:
	.string "BLACKTHORN CITY\n"
	.string "A Quiet Mountain Retreat$"

BlackthornCity_Text_CoolTrainerF:
	.string "Training POKeMON isn't just\n"
	.string "about winning battles.\p"
	.string "It's about building bonds.$"

BlackthornCity_Text_CoolTrainerF2:
	.string "CLAIR is incredibly strong.\n"
	.string "Her Dragon POKeMON are\l"
	.string "fearsome in battle!$"

BlackthornCity_Text_DragonsDenSign:
	.string "DRAGON's DEN\n"
	.string "Sacred Training Ground$"

BlackthornCity_Text_GymBoy:
	.string "CLAIR is the strongest GYM\n"
	.string "LEADER in JOHTO.\p"
	.string "She's LANCE's cousin, you\n"
	.string "know!$"

BlackthornCity_Text_GymSign:
	.string "BLACKTHORN CITY POKeMON GYM\n"
	.string "LEADER: CLAIR\p"
	.string "The Blessed User of\n"
	.string "Dragon POKeMON$"

BlackthornCity_Text_MoveHouseSign:
	.string "MOVE DELETER's HOUSE\n"
	.string "Unwanted Moves Forgotten!$"

BlackthornCity_Text_Santos:
	.string "The mountains around here are\n"
	.string "harsh, but the people of\l"
	.string "BLACKTHORN are tougher.\p"
	.string "We raise Dragon POKeMON with\n"
	.string "pride!$"

BlackthornCity_Text_Youngster:
	.string "I want to catch every kind of\n"
	.string "POKeMON in JOHTO!$"

