OlivineCity_House2_MapScripts::
	.byte 0

@ Johto map scripts (imported from HnS, stubs)

OlivineCity_EventScript_Punisher::
	msgbox OlivineCity_House2_Text_Punisher, MSGBOX_NPC
	end

OlivineCity_EventScript_PunisherBoy::
	msgbox OlivineCity_House2_Text_PunisherBoy, MSGBOX_NPC
	end

OlivineCity_House2_Text_Punisher:
	.string "I've been knitting a sweater\n"
	.string "for my MEOWTH.\p"
	.string "It gets cold by the sea!$"

OlivineCity_House2_Text_PunisherBoy:
	.string "Mom's MEOWTH scratches the\n"
	.string "furniture all the time!\p"
	.string "But we still love it!$"

