SafariZoneGate_PokemonCenter_MapScripts::
	.byte 0

@ Johto map scripts (imported from HnS, stubs)

SafariZoneGate_PokemonCenter_EventScript_NPC1::
	msgbox SafariZoneGate_PokemonCenter_Text_NPC1, MSGBOX_NPC
	end

SafariZoneGate_PokemonCenter_EventScript_NPC2::
	msgbox SafariZoneGate_PokemonCenter_Text_NPC2, MSGBOX_NPC
	end

SafariZoneGate_PokemonCenter_Text_Boy::
	msgbox SafariZoneGate_PokemonCenter_Text_Boy, MSGBOX_NPC
	end


SafariZoneGate_PokemonCenter_Text_NPC1:
	.string "...$"

SafariZoneGate_PokemonCenter_Text_NPC2:
	.string "...$"
