MtSilver_1F_WaterfallRoom_MapScripts::
	.byte 0

@ Johto map scripts (imported from HnS, stubs)

MtSilver_1F_WaterfallRoom_EventScript_DireHit::
	msgbox MtSilver_1F_WaterfallRoom_Text_DireHit, MSGBOX_NPC
	end

MtSilver_1F_WaterfallRoom_EventScript_FullRestore::
	msgbox MtSilver_1F_WaterfallRoom_Text_FullRestore, MSGBOX_NPC
	end

MtSilver_1F_WaterfallRoom_EventScript_MaxPotion::
	msgbox MtSilver_1F_WaterfallRoom_Text_MaxPotion, MSGBOX_NPC
	end

MtSilver_1F_WaterfallRoom_EventScript_UltraBall::
	msgbox MtSilver_1F_WaterfallRoom_Text_UltraBall, MSGBOX_NPC
	end


MtSilver_1F_WaterfallRoom_Text_DireHit:
	.string "...$"

MtSilver_1F_WaterfallRoom_Text_FullRestore:
	.string "...$"

MtSilver_1F_WaterfallRoom_Text_MaxPotion:
	.string "...$"

MtSilver_1F_WaterfallRoom_Text_UltraBall:
	.string "...$"
