GoldenrodCity_House3_MapScripts::
	.byte 0

@ Johto map scripts (imported from HnS, stubs)

GoldenrodCity_House3_EventScript_PokefanM::
	msgbox GoldenrodCity_House3_Text_PokefanM, MSGBOX_NPC
	end

GoldenrodCity_House3_EventScript_Twin::
	msgbox GoldenrodCity_House3_Text_Twin, MSGBOX_NPC
	end

GoldenrodCity_House3_Text_PokefanM:
	.string "My POKeMON is the cutest!\n"
	.string "Don't you think so too?$"


GoldenrodCity_House3_Text_Twin:
	.string "My sibling and I both love\nPOKeMON!$"
