GoldenrodCity_RadioTower_2F_MapScripts::
	.byte 0

@ Johto map scripts (imported from HnS, stubs)

GoldenrodCity_RadioTower_2F_EventScript_Boy::
	msgbox GoldenrodCity_RadioTower_2F_Text_Boy, MSGBOX_NPC
	end

GoldenrodCity_RadioTower_2F_EventScript_Buena::
	msgbox GoldenrodCity_RadioTower_2F_Text_Buena, MSGBOX_NPC
	end

GoldenrodCity_RadioTower_2F_EventScript_Jigglypuff::
	msgbox GoldenrodCity_RadioTower_2F_Text_Jigglypuff, MSGBOX_NPC
	end

GoldenrodCity_RadioTower_2F_EventScript_Policeman::
	msgbox GoldenrodCity_RadioTower_2F_Text_Policeman, MSGBOX_NPC
	end

GoldenrodCity_RadioTower_2F_EventScript_Sign1::
	msgbox GoldenrodCity_RadioTower_2F_Text_Sign1, MSGBOX_SIGN
	end

GoldenrodCity_RadioTower_2F_EventScript_Sign2::
	msgbox GoldenrodCity_RadioTower_2F_Text_Sign2, MSGBOX_SIGN
	end

GoldenrodCity_RadioTower_2F_EventScript_Teacher::
	msgbox GoldenrodCity_RadioTower_2F_Text_Teacher, MSGBOX_NPC
	end

GoldenrodRaidoTower2_EventScript_Grunt3::
	msgbox GoldenrodRaidoTower2_Text_Grunt3, MSGBOX_NPC
	end

GoldenrodRaidoTower2_EventScript_Grunt4::
	msgbox GoldenrodRaidoTower2_Text_Grunt4, MSGBOX_NPC
	end

GoldenrodRaidoTower2_EventScript_Grunt5::
	msgbox GoldenrodRaidoTower2_Text_Grunt5, MSGBOX_NPC
	end

GoldenrodRaidoTower2_EventScript_GruntF2::
	msgbox GoldenrodRaidoTower2_Text_GruntF2, MSGBOX_NPC
	end

GoldenrodCity_RadioTower_2F_Text_Boy:
	.string "Did you know there are POKeMON\n"
	.string "you can only find at night?$"


GoldenrodCity_RadioTower_2F_Text_Buena:
	.string "...$"

GoldenrodCity_RadioTower_2F_Text_Jigglypuff:
	.string "...$"

GoldenrodCity_RadioTower_2F_Text_Policeman:
	.string "This is a nice place.\nThe people here are friendly.$"

GoldenrodCity_RadioTower_2F_Text_Sign1:
	.string "GoldenrodCity RadioTower 2F$"

GoldenrodCity_RadioTower_2F_Text_Sign2:
	.string "GoldenrodCity RadioTower 2F$"

GoldenrodCity_RadioTower_2F_Text_Teacher:
	.string "Knowledge is the key to\nbecoming a great TRAINER!$"

GoldenrodRaidoTower2_Text_Grunt3:
	.string "...$"

GoldenrodRaidoTower2_Text_Grunt4:
	.string "...$"

GoldenrodRaidoTower2_Text_Grunt5:
	.string "...$"

GoldenrodRaidoTower2_Text_GruntF2:
	.string "...$"
