SproutTower_2F_MapScripts::
	.byte 0

@ Johto map scripts (imported from HnS, stubs)

SproutTower_2F_EventScript_SageEdmond::
	msgbox SproutTower_2F_Text_SageEdmond, MSGBOX_NPC
	end

SproutTower_2F_EventScript_SageNico::
	msgbox SproutTower_2F_Text_SageNico, MSGBOX_NPC
	end

SproutTower_2F_EventScript_Xdefend::
	msgbox SproutTower_2F_Text_Xdefend, MSGBOX_NPC
	end


SproutTower_2F_Text_SageEdmond:
	.string "Wisdom comes with patience\nand understanding.$"

SproutTower_2F_Text_SageNico:
	.string "Wisdom comes with patience\nand understanding.$"

SproutTower_2F_Text_Xdefend:
	.string "...$"
