NewBarkTown_House1_MapScripts::
	.byte 0

NewBarkTown_House1_EventScript_Daughter::
	msgbox NewBarkTown_House1_Text_Daughter, MSGBOX_NPC
	end

NewBarkTown_House1_EventScript_Mother::
	msgbox NewBarkTown_House1_Text_Mother, MSGBOX_NPC
	end

NewBarkTown_House1_Text_Daughter:
	.string "I want to be a POKeMON TRAINER\n"
	.string "when I grow up!\p"
	.string "Just like you!$"

NewBarkTown_House1_Text_Mother:
	.string "NEW BARK TOWN is so peaceful.\n"
	.string "The breeze from the sea is\l"
	.string "always so refreshing.$"

