Route26_MapScripts::
	.byte 0

@ Johto map scripts (imported from HnS, stubs)

Route26_EventScript_Gaven::
	msgbox Route26_Text_Gaven, MSGBOX_NPC
	end

Route26_EventScript_Jake::
	msgbox Route26_Text_Jake, MSGBOX_NPC
	end

Route26_EventScript_Joyce::
	msgbox Route26_Text_Joyce, MSGBOX_NPC
	end

Route26_EventScript_Richard::
	msgbox Route26_Text_Richard, MSGBOX_NPC
	end


Route26_Text_Gaven:
	.string "...$"

Route26_Text_Jake:
	.string "...$"

Route26_Text_Joyce:
	.string "...$"

Route26_Text_Richard:
	.string "...$"
