GoldenrodCity_FlowerShop_MapScripts::
	.byte 0

@ Johto map scripts (imported from HnS, stubs)

GoldenrodCity_FlowerShop_EventScript_Floria1::
	msgbox GoldenrodCity_FlowerShop_Text_Floria1, MSGBOX_NPC
	end

GoldenrodCity_FlowerShop_EventScript_Owner::
	msgbox GoldenrodCity_FlowerShop_Text_Owner, MSGBOX_NPC
	end

Route104_PrettyPetalFlowerShop_EventScript_MintOwner::
	msgbox Route104_PrettyPetalFlowerShop_Text_MintOwner, MSGBOX_NPC
	end


GoldenrodCity_FlowerShop_Text_Floria1:
	.string "...$"

GoldenrodCity_FlowerShop_Text_Owner:
	.string "...$"

Route104_PrettyPetalFlowerShop_Text_MintOwner:
	.string "...$"
