GoldenrodCity_DepartmentStore_6F_MapScripts::
	.byte 0

@ Johto map scripts (imported from HnS, stubs)

GoldenrodCity_DepartmentStore_6F_EventScript_Jose::
	msgbox GoldenrodCity_DepartmentStore_6F_Text_Jose, MSGBOX_NPC
	end

GoldenrodDeptStore6_EventScript_Lass::
	msgbox GoldenrodDeptStore6_Text_Lass, MSGBOX_NPC
	end

GoldenrodDeptStore6_EventScript_Nerd::
	msgbox GoldenrodDeptStore6_Text_Nerd, MSGBOX_NPC
	end

GoldenrodDeptStore6_EventScript_Sign::
	msgbox GoldenrodDeptStore6_Text_Sign, MSGBOX_SIGN
	end

GoldenrodDeptStore6_EventScript_Whitney::
	msgbox GoldenrodDeptStore6_Text_Whitney, MSGBOX_NPC
	end

GoldenrodDeptStore6_Text_Lass:
	.string "I love walking around town.\n"
	.string "The fresh air is wonderful!$"


GoldenrodCity_DepartmentStore_6F_Text_Jose:
	.string "...$"

GoldenrodDeptStore6_Text_Nerd:
	.string "I have been researching the\nlocal POKeMON population.$"

GoldenrodDeptStore6_Text_Sign:
	.string "GoldenrodCity DepartmentStore 6F$"

GoldenrodDeptStore6_Text_Whitney:
	.string "...$"
