GoldenrodCity_PokemonCenter_MapScripts::
	.byte 0

@ Johto map scripts (imported from HnS, stubs)

GoldenrodCity_PokemonCenter_EventScript_GbaKid1::
	msgbox GoldenrodCity_PokemonCenter_Text_GbaKid1, MSGBOX_NPC
	end

GoldenrodCity_PokemonCenter_EventScript_GbaKid2::
	msgbox GoldenrodCity_PokemonCenter_Text_GbaKid2, MSGBOX_NPC
	end

GoldenrodCity_PokemonCenter_EventScript_Granny::
	msgbox GoldenrodCity_PokemonCenter_Text_Granny, MSGBOX_NPC
	end

GoldenrodCity_PokemonCenter_EventScript_Lass::
	msgbox GoldenrodCity_PokemonCenter_Text_Lass, MSGBOX_NPC
	end

GoldenrodCity_PokemonCenter_Text_Lass:
	.string "I love walking around town.\n"
	.string "The fresh air is wonderful!$"


GoldenrodCity_PokemonCenter_Text_GbaKid1:
	.string "I am going to be a TRAINER\nsomeday! Just you wait!$"

GoldenrodCity_PokemonCenter_Text_GbaKid2:
	.string "I am going to be a TRAINER\nsomeday! Just you wait!$"

GoldenrodCity_PokemonCenter_Text_Granny:
	.string "Would you like some tea, dear?\nYou look tired from traveling.$"
