Route38_MapScripts::
	.byte 0

@ Johto map scripts (imported from HnS, stubs)

Route38_EventScript_Chad::
	msgbox Route38_Text_Chad, MSGBOX_NPC
	end

Route38_EventScript_Dana::
	msgbox Route38_Text_Dana, MSGBOX_NPC
	end

Route38_EventScript_Harry::
	msgbox Route38_Text_Harry, MSGBOX_NPC
	end

Route38_EventScript_Item_LaxIncense::
	msgbox Route38_Text_Item_LaxIncense, MSGBOX_NPC
	end

Route38_EventScript_Olivia::
	msgbox Route38_Text_Olivia, MSGBOX_NPC
	end

Route38_EventScript_Sign1::
	msgbox Route38_Text_Sign1, MSGBOX_SIGN
	end

Route38_EventScript_Sign2::
	msgbox Route38_Text_Sign2, MSGBOX_SIGN
	end

Route38_EventScript_Toby::
	msgbox Route38_Text_Toby, MSGBOX_NPC
	end

Route38_EventScript_Valerie::
	msgbox Route38_Text_Valerie, MSGBOX_NPC
	end


Route38_Text_Chad:
	.string "...$"

Route38_Text_Dana:
	.string "...$"

Route38_Text_Harry:
	.string "...$"

Route38_Text_Item_LaxIncense:
	.string "...$"

Route38_Text_Olivia:
	.string "...$"

Route38_Text_Sign1:
	.string "Route38$"

Route38_Text_Sign2:
	.string "Route38$"

Route38_Text_Toby:
	.string "...$"

Route38_Text_Valerie:
	.string "...$"
